# Generated by Django 4.0.4 on 2022-04-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_banks', '0002_remove_bankaccount_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='banckName',
            new_name='bankName',
        ),
    ]
